export const GET_ORIGINALS = 'GET ORIGINALS'
export const GET_TRENDINGMOVIES ='GET_TRENDINGMOVIES';
export const GET_TOPRATED = 'GET_TOPRATED';
export const GET_ACTION = 'GET_ACTION';
export const GET_COMEDY = 'GET_COMEDY';
export const GET_HORROR = 'GET_HORROR';
export const GET_ROMANTIC = 'GET_ROMANTIC';
export const GET_DOCUMENT = 'GET_DOCUMENT';

export const SET_MOVIE_DETAIL = 'SET_MOVIE_DETAIL';